
serverName: UUID

auth:
  type: http
  options:
    endpointUrl: https://wt-kyle-seiyria_com-0.run.webtask.io/landoftherair-auth
    permittedStatusCodes: [200]
    requestTimeout: 5000

permission:
  type: config
  options:
    path: ./ds.permissions.yml
    maxRuleIterations: 3
    cacheEvaluationInerval: 60000
