apiVersion: v1
kind: Service
metadata:
  labels:
    kube.service: database
  name: database
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    kube.service: database
status:
  loadBalancer: {}
