apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    kube.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        kube.service: server
    spec:
      containers:
      - image: server
        imagePullPolicy: Never
        name: server
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
