apiVersion: v1
kind: Service
metadata:
  labels:
    kube.service: server
  name: server
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    kube.service: server
status:
  loadBalancer: {}
